# Generated by Django 6.0.1 on 2026-03-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sosrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DISPATCHED', 'Dispatched'), ('ON_ROUTE', 'On Route'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
