# Generated by Django 6.0.1 on 2026-03-11 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0009_ambulance'),
        ('sos', '0003_alter_sosrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sosrequest',
            name='ambulance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sos', to='hospitals.ambulance'),
        ),
    ]
