# Generated by Django 6.0.1 on 2026-02-24 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_positive', models.IntegerField(default=0)),
                ('a_negative', models.IntegerField(default=0)),
                ('b_positive', models.IntegerField(default=0)),
                ('b_negative', models.IntegerField(default=0)),
                ('o_positive', models.IntegerField(default=0)),
                ('o_negative', models.IntegerField(default=0)),
                ('ab_positive', models.IntegerField(default=0)),
                ('ab_negative', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hospitals.hospital')),
            ],
        ),
    ]
