# Generated by Django 6.0.1 on 2026-02-26 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0004_hospital_latitude_hospital_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='longitude',
        ),
    ]
