# Generated by Django 6.0.1 on 2026-03-08 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0006_hospital_latitude_hospital_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='citizen',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='hospital',
        ),
        migrations.DeleteModel(
            name='BloodAvailability',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
