# Generated by Django 6.0.1 on 2026-03-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0007_remove_feedback_citizen_remove_feedback_hospital_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('report_type', models.CharField(max_length=100)),
                ('report_date', models.DateField()),
                ('report_file', models.FileField(upload_to='reports/')),
                ('report_hash', models.CharField(max_length=256)),
            ],
        ),
    ]
